name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name : Navigate to page directory
        run: cd page

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload docs
        uses: actions/upload-artifact@v4
        with:
          name: page
          path: ./dist
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download page
        uses: actions/download-artifact@v4
        with:
          name: page

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
